// Sriramajayam

/** \file vm_Manager.h
 * \brief Defines main class vm::Manager that performs face agglomeration and vertex relaxation operations
 * \author Ramsharan Rangarajan
 */

#pragma once

#include <pmp/SurfaceMesh.h>
#include <vm_utils.h>
#include <string>
#include <tuple>
#include <map>

namespace vm
{
  class Manager;
  using MeshUpdateCallback_f = std::function<void(const int merge_num, const pmp::SurfaceMesh &mesh, Manager &manager)>;

  /** \brief Class implementing the main functionality of the library.
   *
   * ---
   *
   * **The Mesh**: \n
   * The class maintains a persistent copy of the underlying mesh. \n
   * The mesh is represented as an instance of pmp::SurfaceMesh. No other types are supported.\n
   * The mesh has the following  properties:
   *
   * | Property  | Attribute | Data type | Purpose |
   * |-----------|-----------|-----------|----------|
   * |`vertex_quality` | Vertex property | double | Vertex quality, evaluated with a user-specified metric |
   * | `face_quality` | Face property | double | Face quality, evaluated with a user-specified metric |
   * | `interface_id` | Vertex property | int | Identifier of interface on which a vertex lies; -1 for vertices not lying on an interface |
   * | `domain_id` | Face property | int | Identifier of domain to which a face belongs |
   *
   * The class provides immutable external access to the mesh. \n
   * The assignment of domain and interface identifiers to faces and vertices is required at construction
   * 
   * ---
   *
   * **Element agglomeration**: \n
   * One of the two main functionalities provided by the class is element agglomeration. \n
   * Element agglomeration attempts to merge faces with their neighors to improve quality, as defined by a user-specified metric. \n
   * The operation changes the element count and connectivity of the mesh, but leaves the vertex set unchanged.\n
   * Given a face quality metric \f$Q\f$, the class enables merging a face \f$f\f$ with a neighbor \f$n_f\f$ to create a new face \f$g\f$, provided that:
   * - the set of *agglomerable* neighbors \f${\cal A}(f)\f$ is not empty. 
   * - \f$Q(g)>\epsilon\f$ for a given lower bound \f$\epsilon\f$ for face quality, and
   * - \f$Q(g)\geq \eta Q(f)\f$, i.e., the quality of \f$g\f$ is improved sufficiently over \f$f\f$.
   * The quality of the agglomerated neighbor \f$n_f\f$ may deteriorate as a result. This is essential- it is  precisely why improvement is possible in the first place.
   * Faces of better quality are compromised to improve the qualities of poorer faces.
   *
   * The class provides three overloaded methods for element agglomeration:
   * - `merge_face()` attempts to agglomerate a specified face. It provides the most granular control.
   * - `merge_faces(S,...)` attempts agglomerating faces in a specified subset of faces `S`, starting from the poorest one first.
   * - `merge_faces()` performs a mesh-wide search to tag faces with quality below the specified threshold \f$\epsilon\f$, before attempting to agglomerate these.
   *
   * ---
   *
   * **Vertex relaxation**: \n
   * The second functionality provided by the class is vertex relaxation. \n
   * This operation perturbs a vertex not belonging to an interface, to a new location to improve the qualities of incident faces. \n
   * Specifically, let \f$f_1, \ldots, f_n\f$ be the set of faces incident at a vertex \f$v\f$. \n
   * Denote the quality of an incident face \f$f\f$ with \f$v\f$ positioned at \f$x\f$ as \f$Q(f;x)\f$. \n
   * The class identifies a new location \f$y\f$ for \f$v\f$ such that: 
   * \f[\min_{1\leq i\leq n}Q(f_i,y) > \min_{1\leq i\leq n}Q(f_i,x)\f] 
   * It is useful to interpret \f$\min_{1\leq i\leq n}Q(f_i,x)\f$ as the quality of the vertex \f$v\f$.
   *
   * Candidate locations for the new vertex position are generated by random sampling.
   * The number of samples to generate is specified by the user.
   *
   * 
   * The class provides three overloaded methods for vertex relaxation:
   * - `move_vertex` attempts to relocate a specified vertex to a new location
   * - `move_vertices(S,\ldots)` attempts to relocate vertices in a specified set `S`, starting from the vertex with the poorest quality.  
   * - `move_vertices` performs a mesh-wide search to tag vertices with quality below a specified threshold \f$\epsilonf\f$, and subsequently attempts to relax them
   * 
   * ---
   *
   * **Accessing face qualities**: \n
   * Face qualities are stored under the `face_quality` property in the mesh. \n
   * Vertex qualities are stored under the `vertex_quality` property in the mesh. \n
   * These can be directly accessed from the mesh. \n
   * Note that both qualities are rendered obsolete after element agglomeration or vertex relaxation operations. \n
   * Calling `compute_qualities()` recomputes face and vertex qualities mesh-wide.
   * 
   * ---
   */
  class Manager
  {
  public:
    //! \brief Constructor, with mesh initialization from a vtk or off file
    //! Runs checks on the mesh after initialization
    //! \param[in] Input file with mesh, assumed to be of type .vtk or .off
    Manager(const std::string filename);

    //! \brief Constructor, with mesh copied from a given instance
    //! Assumes that the mesh has the vertex property `interface_id` and face property `domain_id` defined
    //! The `vertex_quality` and `face_quality` properties are optional. If provided, they are copied.
    //! \param[in] in_mesh Input mesh, copied
    Manager(const pmp::SurfaceMesh& in_mesh);
    
    //! \brief Destructor
    ~Manager() = default;

    //! Disable copy and assignment
    Manager(const Manager&) = delete;
    Manager operator=(const Manager&) = delete;

    //! \brief Inspects the validatity of a mesh 
    //!
    //! Runs the following checks:
    //! - face property `material_id` must exist
    //! - vertex property `interface_id` must exist
    //! - integrity checks using the function vm::inspect_mesh
    inline void inspect_mesh() const {
      assert(mesh.has_face_property("material_id")==true);
      assert(mesh.has_vertex_property("interface_id")==true);
      bool flag = vm::inspect_mesh(mesh); assert(flag && "Mesh is invalid");
    }
    
    //! \brief Immutable access to the mesh
    //! \return Const reference to the mesh
    inline pmp::SurfaceMesh& get_mesh()
    { return mesh; }
    
    //! \brief Agglomerate a face with a feasible neighbor
    //! \param[in] f The face
    //! \param[in] qface Quality metric to use
    //! \param[in] qthreshold Acceptable positive lower bound for quality
    //! \param[in] improve_factor Lower bound for factor of improvement in face quality, assumed to be greater than of equal to 1.
    //! \return A pair `result` such that:
    //! - `result->first`: true if the face was agglomerated, and false otherwise
    //! - `result->second`: the new agglomerated face if `result->first=true`, and equal to `f` otherwise
    std::pair<bool, pmp::Face> merge_face(const pmp::Face& f, FaceQuality_f qface, const double qthreshold, const double qimprove_factor);

    //! \brief Agglomerate a given set of faces
    //! \param[in] subset Subset of faces in the mesh to attempt agglomerating
    //! \param[in] qface Face quality metric to use
    //! \param[in] qthreshold Acceptable positive lower bound for quality
    //! \param[in] improve_factor Lower bound for factor of improvement in face quality, assumed to be greater than of equal to 1.
    //! \return Number of merged faces
    int merge_faces(const std::set<pmp::Face>& subset, 
		    FaceQuality_f qface, const double qthreshold, const double improve_factor, MeshUpdateCallback_f callback=nullptr);

    //! \brief Agglomerate faces in a mesh
    //! Attempts merging all faces satisfying \f$Q(f)\leq \epsilon\f$ for the given quality threshold \f$\epsilon\f$.
    //! \param[in] qface Face quality metric to use
    //! \param[in] qthreshold Acceptable positive lower bound for quality
    //! \param[in] improve_factor Lower bound for factor of improvement in face quality, assumed to be greater than of equal to 1.
    //! \return Number of merged faces									
    int merge_faces(FaceQuality_f qface, const double qthreshold, const double improve_factor, MeshUpdateCallback_f callback=nullptr);

    // moves a vertex to a more favorable position
    std::pair<bool,double> move_vertex(const pmp::Vertex& vertex, const int num_poly_samples,
				       const int num_edge_samples, MeshVertexQuality_f qfunc);

    // moves vertices
    int move_vertices(MeshVertexQuality_f qfunc, const double qthreshold,
		      const int num_poly_samples, const int num_edge_samples,
		      const std::set<int> interface_ids,
		      MeshUpdateCallback_f callback=nullptr);
    
     // compute face qualities in the mesh. saved under face property "quality"
    void compute_face_qualities(FaceQuality_f qfunc);

    // compute vertex qualities in the mesh. saved under vertex property "quality"
    void compute_vertex_qualities(MeshVertexQuality_f qfunc);
    
    // visualize
    void write_mesh(const std::string filename);

  private:
    // identify the face along which to merger a given face
    static std::tuple<bool, double, pmp::Halfedge> find_halfedge_for_face_merge(const pmp::SurfaceMesh& mesh, const pmp::Face& face, FaceQuality_f qfunc);
    
    // Agglomerate faces along prescribed edge
    static void merge_face(pmp::SurfaceMesh& mesh, const pmp::Halfedge& halfedge);

    // identify a feasible point to move a vertex
    static std::tuple<bool, pmp::Point, double> compute_improved_vertex_position(pmp::SurfaceMesh          &mesh,
										 const pmp::Vertex         &vertex,
										 const int                 num_poly_samples,
										 const int                 num_edge_samples,
										 const MeshVertexQuality_f qfunc);
    // random generation of feasible vertex positions
    static std::vector<std::pair<double,double>>
      compute_feasible_vertex_positions(const pmp::SurfaceMesh& mesh,
					const pmp::Vertex&      vertex,
					const int               num_poly_samples,        // max number of random positions to generate
					const int               num_edge_samples);       // number of samples to generate per edge  
    pmp::SurfaceMesh mesh;
  };
}
